[package]
name = "flashpoint-archive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
chrono = "0.4.31"
rusqlite = { version = "0.30.0", features = ["chrono", "array", "bundled"] }
snafu = "0.8.0"
rusqlite_migration = "1.1.0"
uuid = { version = "1.6.1", features = ["v4"] }

[dev_dependencies]
criterion = "0.5.1"

[[bench]]
name = "db_bench"
harness = false
